[package]
name = "des"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
cipher-core.workspace = true
zeroize.workspace = true

[dev-dependencies]
claims.workspace = true
rand.workspace = true
rstest.workspace = true

[lints]
workspace = true
