[package]
name = "cipher-core"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
zeroize.workspace = true

[dev-dependencies]
claims.workspace = true

[lints]
workspace = true
